application: nikcub
version: 5
runtime: python
api_version: 1
default_expiration: "1h"

handlers:
# cached posts
# - url: /
#   static_files: cache/index
#   upload: cache/index
#   mime_type: text/html
#   expiration: 4h
#
# - url: /posts/(.*)
#   static_files: cache/\1
#   upload: cache/(.*)
#   mime_type: text/html
#   expiration: 10m
# 
# - url: /
#   static_files: cache/index
#   upload: cache/index
#   mime_type: text/html
#   expiration: 5m
# 
# - url: /(contact|about|archive|consulting|projects|feed-rss)
#   static_files: cache/\1
#   upload: cache/(.*)
#   mime_type: text/html
#   expiration: 1h

- url: /google6492338f4f40e3db.html
  static_files: static/google6492338f4f40e3db.html
  upload: static/google6492338f4f40e3db.html
  mime_type: text/html

- url: /fb-headers.txt
  static_files: static/fb-headers.txt
  upload: static/fb-headers.txt
  mime_type: text/plain
  expiration: 30d

- url: /fb-table.html
  static_files: static/fb-table.html
  upload: static/fb-table.html
  mime_type: text/html
  expiration: 30d

- url: /bsd-license.txt
  static_files: static/bsd-license.txt
  upload: static/bsd-license.txt
  mime_type: text/plain
  expiration: 30d

- url: /bsd-license
  static_files: static/bsd-license.txt
  upload: static/bsd-license.txt
  mime_type: text/plain
  expiration: 30d

# Most browsers request favicon
- url: /touch-icon.png
  static_files: static/touch-icon.png
  upload: static/touch-icon.png
  mime_type: image/png
  expiration: 30d

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration: 30d

# Most bots request robots
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  mime_type: text/plain
  expiration: 30d  

- url: /humans.txt
  static_files: static/humans.txt
  upload: static/humans.txt
  mime_type: text/plain
  expiration: 1h  
  
- url: /projects/forcessl.crx
  static_files: static/fidelio-1.0.4.crx
  upload: static/fidelio-1.0.4.crx
  mime_type: application/x-chrome-extension
  expiration: 1m

- url: /projects/force-ssl.crx
  static_files: static/fidelio-1.0.4.crx
  upload: static/fidelio-1.0.4.crx
  mime_type: application/x-chrome-extension
  expiration: 1m

- url: /projects/parley.crx
  static_files: static/parley.crx
  upload: static/parley.crx
  mime_type: application/x-chrome-extension
  expiration: 1m

- url: /projects/fidelio.crx
  static_files: static/fidelio-1.0.4.crx
  upload: static/fidelio-1.0.4.crx
  mime_type: application/x-chrome-extension
  expiration: 1m

- url: /projects/blockplus.crx
  static_files: static/blockplus-4.crx
  upload: static/blockplus-4.crx
  mime_type: application/x-chrome-extension
  expiration: 1d
  
- url: /projects/blockplus/updates.xml
  static_files: static/blockplus-updates.xml
  upload: static/blockplus-updates.xml
  expiration: 1d

- url: /projects/fidelio/updates.xml
  static_files: static/fidelio-updates.xml
  upload: static/fidelio-updates.xml
  expiration: 1m

- url: /projects/force-ssl/updates.xml
  static_files: static/forcessl-updates.xml
  upload: static/forcessl-updates.xml
  expiration: 1m

- url: /projects/parley/updates.xml
  static_files: static/parley-updates.xml
  upload: static/forcessl-updates.xml
  expiration: 1m

# Static file mappings
- url: /css/nikcub.([0-9]+).css
  mime_type: text/css
  static_files: static/css/nikcub.css
  upload: static/css/nikcub.css
  expiration: 30d  
  
- url: /css/nikcub.([0-9]+).min.css
  mime_type: text/css
  static_files: static/css/nikcub.min.css
  upload: static/css/nikcub.min.css
  expiration: 30d  
  
- url: /css
  mime_type: text/css
  expiration: 10000d
  static_dir: static/css
- url: /img
  static_dir: static/img
  expiration: 10000d
- url: /js
  static_dir: static/js
  expiration: 10000d
  
# Catch-all for static files
- url: /static
  static_dir: static
  expiration: 30d  

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
    
# Drop through to app if none of the above. Handle 404 in app
- url: .*
  script: main.py

error_handlers:
- file: templates/server_error.html
- error_code: over_quota
  file: templates/server_error.html
- error_code: dos_api_denial
  file: templates/server_error.html
- error_code: timeout
  file: templates/server_error.html
  
builtins:
- appstats: on
- admin_redirect: on
- remote_api: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/git/.*
- ^(.*/)?.*/svn/.*
- ^(.*/)?\..*
- ^(.*/)?README$
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.sh$
- ^(.*/)?.*\.sql3$