application: nikcub
version: 0-2-dev
runtime: python
api_version: 1
default_expiration: "1h"

handlers:
# Most browsers request favicon
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  
# Most bots request robots
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  mime_type: text/plain

- url: /projects/forcessl.crx
  static_files: static/force-ssl.crx
  upload: static/force-ssl.crx
  mime_type: application/x-chrome-extension
  expiration: 1m

- url: /projects/force-ssl.crx
  static_files: static/force-ssl.crx
  upload: static/force-ssl.crx
  mime_type: application/x-chrome-extension
  expiration: 1m

- url: /projects/parley.crx
  static_files: static/parley.crx
  upload: static/parley.crx
  mime_type: application/x-chrome-extension
  expiration: 1m

- url: /projects/fidelio.crx
  static_files: static/fidelio.crx
  upload: static/fidelio.crx
  mime_type: application/x-chrome-extension
  expiration: 1m

- url: /projects/fidelio/updates.xml
  static_files: static/fidelio-updates.xml
  upload: static/fidelio-updates.xml
  expiration: 1m

- url: /projects/force-ssl/updates.xml
  static_files: static/forcessl-updates.xml
  upload: static/forcessl-updates.xml
  expiration: 1m

# Static file mappings
- url: /css
  mime_type: text/css
  expiration: 10000d
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
  
# Catch-all for static files
- url: /static
  static_dir: static

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
    
# Drop through to app if none of the above. Handle 404 in app
- url: .*
  script: main.py

error_handlers:
- file: templates/server_error.html
- error_code: over_quota
  file: templates/server_error.html
- error_code: dos_api_denial
  file: templates/server_error.html
- error_code: timeout
  file: templates/server_error.html
  
builtins:
- datastore_admin: on
- appstats: on
- admin_redirect: on

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/git/.*
- ^(.*/)?.*/svn/.*
- ^(.*/)?\..*
- ^(.*/)?README$
- ^(.*/)?.*\.bak$